RELAX    ARG        t
RELAX    ASN        t
RELAX    ASP        t
RELAX    CYS        t
RELAX    GLN        t
RELAX    GLU        t
RELAX    HIS        t
RELAX    ILE        t
RELAX    LEU        t
RELAX    LYS        t
RELAX    MET        t
RELAX    PAA        t
RELAX    PDD        t
RELAX    PHE        t
RELAX    SER        t
RELAX    TRP        t
RELAX    TYR        t
RELAX    VAL        t
RELAX    HOH        t
RELAX    _CL        t
